.github/settings.yml
> Add github settings @npm/security team
* n/a
=> chore: add github settings @npm/security team

.github/workflows/default.yml, .github/workflows/issue.yml, .github/workflows/pulls.yml
> Update github actions to latest event support  
> https://help.github.com/en/articles/events-that-trigger-workflows  
* n/a
=> fix(workflows): update github actions to latest event support

.github/settings.yml
> Change robot-write team to admin
* n/a
=> fix(settings): change probot settings robot-write team to admin

.github/semantic.yml
> Change default title and commits to true
* n/a
=> fix(semantic-pull-request): change probot semantic-pull-request default title and commits to true

.github/settings.yml
> Update probot settings repository labels
* n/a
=> fix(settings): update probot settings repository labels

.github/workflows/pulls.yml
> Fix github actions pulls conventional commits format
* Closes https://github.com/npm/sre/issues/116
=> fix(workflows): fix github actions pulls conventional commits format

package-lock.json, package.json
> Add semantic-release npm support to this repository
* Closes https://github.com/npm/sre/issues/118
=> feat(release): add semantic-release npm support to this repository

.github/workflows/default.yml
> Fix semantic-release npm support to this repository
* n/a
=> fix(release): fix semantic-release npm support to this repository

package.json
> Disable npm package release private
* n/a
=> fix(npm): disable npm package release private

.github/settings.yml, .github/workflows/issue.yml, .github/workflows/pulls.yml, package-lock.json, package.json
> Rename npm/github to npm/.github instead
* Closes #15
=> feat(repository): rename npm/github to npm/.github instead

.github/CODEOWNERS, .github/settings.yml
> Transfer repository ownership to cli-team
* n/a
=> chore: transfer repository ownership to cli-team

.github/workflows/pulls.yml, package-lock.json, package.json
> Update semantic-release and @semantic-release dependencies versions
* n/a
=> fix(release): update semantic-release and @semantic-release dependencies versions 

package-lock.json, package.json
> Update dependency semantic-release to v17.1.1
* n/a
=> fix(deps): update dependency semantic-release to v17.1.1

workflow-templates/deploy.properties.json
The icons are being populated from a predefined source
=> fix: icon for deploy workflow template

cloud.js, npm.js
* Add semantic-release branches syntax support
* See https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#branches-properties
=> fix(release): add semantic-release branches syntax support

npm-cli/settings.yml
This will be the file that other cli repos will extend.
=> feat: add npm-cli/settings.yml

workflow-templates/deploy.yaml
This commit adds a reference to our deployment confidence dashboard whenever we deploy this service
=> Links deployment confidence dashboard

.github/workflows/build-container.yaml
A reusable workflow doesn't determine when to run but rather defines
which inputs it receives whenever it runs
=> Adds inputs to the reusable workflow

.github/workflows/build-container.yaml
Similar to what we did previously to inputs we also need to do the
same for secrets
=> Adds secrets to reusable build-container workflow

.github/workflows/build-container.yaml
=> Adds filename input for reusable build container workflow

package-lock.json, package.json
This PR include Caret Ranges `^version` "Compatible with version".
Allows changes that do not modify the left-most non-zero element in the [major, minor, patch] tuple.
Related to: [Dependabot Alerts](https://github.com/github/npm/issues/11852)
=> Caret Ranges 

package-lock.json
This PR include more `package-lock.json` file changes which helps to bump `ip`.
Related to: [Dependabot Alerts](https://github.com/github/npm/issues/11852)
=> lock file changes

package-lock.json
This PR fixes security findings 
Ref: https://github.com/github/npm/issues/12349
=> Fix security findings
